Controllers/CargoController.cs
using Controle_de_Transporte_FrontEnd.Models;
using Controle_de_Transporte_FrontEnd.Service.Interface;
using Microsoft.AspNetCore.Mvc;
using System.Net;

namespace Controle_de_Transporte_FrontEnd.Controllers
{
    public class CargoController : Controller
    {
        private readonly ICargoService _cargoService;
        public CargoController(ICargoService cargoService)
        {
            _cargoService = cargoService;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                var cargos = await _cargoService.GetAllAsync();
                return View(cargos);
            }
            catch (Exception ex)
            {
                return StatusCode((int)HttpStatusCode.InternalServerError, new { Erro = ex.Message });
            }
        }

        public async Task<IActionResult> Details(int id)
        {
            try
            {
                var cargo = await _cargoService.GetByIdAsync(id);
                if (cargo == null)
                {
                    return NotFound();
                }
                return View(cargo);
            }
            catch (Exception ex)
            {
                return StatusCode((int)HttpStatusCode.InternalServerError, new { Erro = ex.Message });
            }
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("NomeCargo")] CargoModel cargo)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var retorno = await _cargoService.AddAsync(cargo);
                    TempData["MensagemSucesso"] = "Cargo cadastrado com sucesso!";
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    TempData["MensagemErro"] = "Erro ao cadastrar o Cargo!";
                    return RedirectToAction("Index");
                }
            }
            return View(cargo);
        }

        public async Task<IActionResult> Edit(int id)
        {
            try
            {
                var cargo = await _cargoService.GetByIdAsync(id);
                if (cargo == null)
                {
                    return NotFound();
                }
                return View(cargo);
            }
            catch (Exception ex)
            {
                return StatusCode((int)HttpStatusCode.InternalServerError, new { Erro = ex.Message });
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,NomeCargo")] CargoModel cargo)
        {
            if (id != cargo.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _cargoService.UpdateAsync(cargo);
                    TempData["MensagemSucesso"] = "Cargo atualizar com sucesso!";
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    TempData["MensagemErro"] = "Erro ao atualizar o Cargo!";
                    return RedirectToAction("Index");
                }
            }
            return View(cargo);
        }     
       
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
               bool cargo =  await _cargoService.DeleteAsync(id);
                if (cargo)
                {
                    TempData["MensagemSucesso"] = "Cargo excluir com sucesso!";
                }
                else
                {
                    TempData["MensagemErro"] = "Erro ao excluir o Cargo!";
                }
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                TempData["MensagemErro"] = "Erro ao excluir o Cargo!";
                return RedirectToAction("Index");
            }
        }
    }
}

Controllers/ManutencaoController.cs
using Controle_de_Transporte_FrontEnd.Models;
using Controle_de_Transporte_FrontEnd.Service.Interface;
using Microsoft.AspNetCore.Mvc;
using System.Net;

namespace Controle_de_Transporte_FrontEnd.Controllers
{
    public class ManutencaoController : Controller
    {
        private readonly IManutencaoService _service;
        public ManutencaoController(IManutencaoService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                var manutencaos = await _service.GetAllAsync();
                return View(manutencaos);
            }
            catch (Exception ex)
            {
                return StatusCode((int)HttpStatusCode.InternalServerError, new { Erro = ex.Message });
            }
        }

        public async Task<IActionResult> Details(int id)
        {
            try
            {
                var manutencaos = await _service.GetByIdAsync(id);
                if (manutencaos == null)
                {
                    return NotFound();
                }
                return View(manutencaos);
            }
            catch (Exception ex)
            {
                return StatusCode((int)HttpStatusCode.InternalServerError, new { Erro = ex.Message });
            }
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TipoManutencao,Custo")] ManutencaoModel manutencao)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var retorno = await _service.AddAsync(manutencao);
                    TempData["MensagemSucesso"] = "Manutenção cadastrado com sucesso!";
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    TempData["MensagemErro"] = "Erro ao cadastrar o Manutenção!";
                    return RedirectToAction("Index");
                }
            }
            return View(manutencao);
        }

        public async Task<IActionResult> Edit(int id)
        {
            try
            {
                var manutencao = await _service.GetByIdAsync(id);
                if (manutencao == null)
                {
                    return NotFound();
                }
                return View(manutencao);
            }
            catch (Exception ex)
            {
                return StatusCode((int)HttpStatusCode.InternalServerError, new { Erro = ex.Message });
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,TipoManutencao,Custo")] ManutencaoModel manutencao)
        {
            if (id != manutencao.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _service.UpdateAsync(manutencao);
                    TempData["MensagemSucesso"] = "Manutenção atualizar com sucesso!";
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    TempData["MensagemErro"] = "Erro ao atualizar o Manutenção!";
                    return RedirectToAction("Index");
                }
            }
            return View(manutencao);
        }

        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                bool manutencao = await _service.DeleteAsync(id);
                if (manutencao)
                {
                    TempData["MensagemSucesso"] = "Manutenção excluir com sucesso!";
                }
                else
                {
                    TempData["MensagemErro"] = "Erro ao excluir o Manutenção!";
                }
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                TempData["MensagemErro"] = "Erro ao excluir o Manutenção!";
                return RedirectToAction("Index");
            }
        }
    }
}

Controllers/UsuarioController.cs
using Controle_de_Transporte_FrontEnd.Models;
using Controle_de_Transporte_FrontEnd.Service.Interface;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Net;

namespace Controle_de_Transporte_FrontEnd.Controllers
{
    public class UsuarioController : Controller
    {
        private readonly IUsuarioService _service;
        private readonly IFuncionariosService _funcService;
        public UsuarioController(IUsuarioService service, IFuncionariosService funcService)
        {
            _service = service;
            _funcService = funcService;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                var usuarios = await _service.GetAllAsync();
                return View(usuarios);
            }
            catch (Exception ex)
            {
                return StatusCode((int)HttpStatusCode.InternalServerError, new { Erro = ex.Message });
            }
        }

        public async Task<IActionResult> Details(int id)
        {
            try
            {
                var usuarios = await _service.GetByIdAsync(id);
                if (usuarios == null)
                {
                    return NotFound();
                }
                return View(usuarios);
            }
            catch (Exception ex)
            {
                return StatusCode((int)HttpStatusCode.InternalServerError, new { Erro = ex.Message });
            }
        }

        public async Task<IActionResult> Create()
        {
            var funcionarios = await ObterFuncionarios();
            ViewBag.Funcionarios = new SelectList(funcionarios, "Id", "NomeFuncionario");

            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(UsuarioModel usuario)
        {
            if (ModelState.IsValid)
            {
                try
                {

                    int funcionarioId = usuario.FuncionarioId;
                    FuncionariosModel funcionario = await ObterFuncionarioPorId(funcionarioId);

                    if (funcionario != null)
                    {

                        usuario.Funcionarios = funcionario;

                        var retorno = await _service.AddAsync(usuario);
                        TempData["MensagemSucesso"] = "Usuario cadastrado com sucesso!";
                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        return NotFound("Funcionario não encontrada");
                    }
                }
                catch (Exception ex)
                {
                    TempData["MensagemErro"] = "Erro ao cadastrado o Usuario!";
                    return RedirectToAction("Index");
                }
            }
            return View(usuario);
        }




        public async Task<IActionResult> Edit(int id)
        {

            try
            {
                var funcionarios = await ObterFuncionarios();
                ViewBag.Funcionarios = new SelectList(funcionarios, "Id", "NomeFuncionario");

                var usuario = await _service.GetByIdAsync(id);
                if (usuario == null)
                {
                    return NotFound();
                }
                return View(usuario);
            }
            catch (Exception ex)
            {
                return StatusCode((int)HttpStatusCode.InternalServerError, new { Erro = ex.Message });
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, UsuarioModel usuario)
        {
            if (id != usuario.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _service.UpdateAsync(usuario);
                    TempData["MensagemSucesso"] = "Usuario atualizar com sucesso!";
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    TempData["MensagemErro"] = "Erro ao atualizar o Usuario!";
                    return RedirectToAction("Index");
                }
            }
            return View(usuario);
        }

        public async Task<IActionResult> Delete(int id)
        {
            try
            {
               bool usuario = await _service.DeleteAsync(id);
                if (usuario)
                {
                    TempData["MensagemSucesso"] = "Usuario excluir com sucesso!";
                }
                else
                {
                    TempData["MensagemErro"] = "Erro ao excluir o Usuario!";
                }
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                TempData["MensagemErro"] = "Erro ao excluir o Usuario!";
                return RedirectToAction(nameof(Index));
            }
        }


        private async Task<List<FuncionariosModel>> ObterFuncionarios()
        {
            var funcionario = new List<FuncionariosModel>();


            var funcionarios = await _funcService.GetAllAsync();


            if (funcionarios != null)
            {

                funcionario.AddRange(funcionarios);
            }

            return funcionario;
        }
        private async Task<FuncionariosModel> ObterFuncionarioPorId(int id)
        {
            if (id <= 0)
            {
                throw new ArgumentException("ID inválido.");
            }

            var funcionario = await _funcService.GetByIdAsync(id);

            return funcionario;
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Controle_de_Transporte_FrontEnd</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Controle_de_Transporte_FrontEnd.styles.css" asp-append-version="true" />
    <link href="https://cdn.datatables.net/v/dt/dt-2.0.5/datatables.min.css" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid ">
                <a class="navbar-brand text-white" asp-area="" asp-controller="transporte" asp-action="Index">Controle de Transporte</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Transporte" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Configurações
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-area="" asp-controller="Cargo" asp-action="Index">Cargo</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Departamento" asp-action="Index">Departamentos</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Funcionarios" asp-action="Index">Funcionarios</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Instituicao" asp-action="Index">Instituições</a>
                                <a class="dropdown-item" asp-area="" asp-controller="MatriculaTransporte" asp-action="Index">Matricula de Transportes</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Manutencao" asp-action="Index">Tipos de Manutenção</a>
                                <a class="dropdown-item" asp-area="" asp-controller="TipoDeTransporte" asp-action="Index">Tipos de Transporte</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Usuario" asp-action="Index">Usuarios</a>
                                <!-- Adicione outras opções de configuração aqui, se necessário -->
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Controle_de_Transporte_FrontEnd - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://cdn.datatables.net/v/dt/dt-2.0.5/datatables.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>

Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Controle_de_Transporte_FrontEnd</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Controle_de_Transporte_FrontEnd.styles.css" asp-append-version="true" />
    <link href="https://cdn.datatables.net/v/dt/dt-2.0.5/datatables.min.css" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid ">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">Controle de Transporte</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>                
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Controle_de_Transporte_FrontEnd - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://cdn.datatables.net/v/dt/dt-2.0.5/datatables.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>