Controllers/TipoDeTransporteController.cs
using Controle_de_Transporte_FrontEnd.Models;
using Controle_de_Transporte_FrontEnd.Service;
using Controle_de_Transporte_FrontEnd.Service.Interface;
using Microsoft.AspNetCore.Mvc;
using System.Net;

namespace Controle_de_Transporte_FrontEnd.Controllers
{
    public class TipoDeTransporteController : Controller
    {
        private readonly ITipodeTransporteService _service;
        public TipoDeTransporteController(ITipodeTransporteService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                var transporte = await _service.GetAllAsync();
                return View(transporte);
            }
            catch (Exception ex)
            {
                return StatusCode((int)HttpStatusCode.InternalServerError, new { Erro = ex.Message });
            }
        }

        public async Task<IActionResult> Details(int id)
        {
            try
            {
                var transporte = await _service.GetByIdAsync(id);
                if (transporte == null)
                {
                    return NotFound();
                }
                return View(transporte);
            }
            catch (Exception ex)
            {
                return StatusCode((int)HttpStatusCode.InternalServerError, new { Erro = ex.Message });
            }
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("NomeTransporte")] TipoDeTransporteModel transporte)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var retorno = await _service.AddAsync(transporte);
                    TempData["MensagemSucesso"] = "Tipo de Transporte cadastrado com sucesso!";
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    TempData["MensagemErro"] = "Erro ao cadastrado o Tipo de Transporte!";
                    return RedirectToAction("Index");
                }
            }
            return View(transporte);
        }

        public async Task<IActionResult> Edit(int id)
        {
            try
            {
                var transporte = await _service.GetByIdAsync(id);
                if (transporte == null)
                {
                    return NotFound();
                }
                return View(transporte);
            }
            catch (Exception ex)
            {
                return StatusCode((int)HttpStatusCode.InternalServerError, new { Erro = ex.Message });
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,NomeTransporte")] TipoDeTransporteModel transporte)
        {
            if (id != transporte.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _service.UpdateAsync(transporte);
                    TempData["MensagemSucesso"] = "Tipo de Transporte atualizar com sucesso!";
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    TempData["MensagemErro"] = "Erro ao atualizar o Tipo de Transporte!";
                    return RedirectToAction("Index");
                }
            }
            return View(transporte);
        }

        public async Task<IActionResult> Delete(int id)
        {
            try
            {
               bool tpTransporte = await _service.DeleteAsync(id);
                if (tpTransporte)
                {
                    TempData["MensagemSucesso"] = "Tipo de Transporte excluir com sucesso!";
                }
                else
                {
                    TempData["MensagemErro"] = "Erro ao excluir o Tipo de Transporte!";
                }
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                TempData["MensagemErro"] = "Erro ao excluir o Tipo de Transporte!";
                return RedirectToAction(nameof(Index));
            }
        }
    }
}

Views/TipoDeTransporte/Create.cshtml
@model TipoDeTransporteModel
@{
    ViewData["Title"] = "Adicionar Tipo de Transporte ";
}
<div class="">

    <h1 class="display-4">Cadastrar Tipo de Transporte</h1>

    <form asp-controller="TipoDeTransporte" asp-action="Create" method="post">

        <div class="form-group">
            <label for="nome">Nome</label>
            <input for="uppercase" type="text" asp-for="NomeTransporte" class="form-control">
            @Html.ValidationMessageFor(x => x.NomeTransporte)

            <br />
            <button type="submit" class="btn btn-primary">Adicionar</button>
            <a class="btn btn-secondary" asp-controller="TipoDeTransporte" asp-action="Index" role="button"> Voltar</a>
    </form>

</div>

Views/TipoDeTransporte/Edit.cshtml
@model TipoDeTransporteModel
@{
    ViewData["Title"] = "Editar Tipo de Transporte";
}
<div class="">
    @if (TempData["MensagemSucesso"] != null)
    {
        <div class="alert alert-success" role="alert">
            <button type="button" class="btn btn-danger  btn-close" arial-label="close"></button>
            @TempData["MensagemSucesso"]
        </div>
    }
    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-danger" role="alert">
            A simple danger alert—check it out!
            <button type="button" class="btn btn-danger  btn-close" arial-label="close"></button>
            @TempData["MensagemErro"]
        </div>
    }

    <br />
    <h1 class="display-4">Editar Tipo de Transporte</h1>

    <form asp-controller="TipoDeTransporte" asp-action="Edit" method="post">

        <input type="hidden" asp-for="Id" />
        <div class="form-group">
            <label for="nome">Nome</label>
            <input type="text" asp-for="NomeTransporte" class="form-control">
            @Html.ValidationMessageFor(x => x.NomeTransporte)
        </div>

        <br />
        <button type="submit" class="btn btn-primary">Alterar</button>
        <a class="btn btn-secondary" asp-controller="TipoDeTransporte" asp-action="Index" role="button"> Voltar</a>
    </form>

</div>

Views/TipoDeTransporte/Index.cshtml
@model List<TipoDeTransporteModel>
@{
    ViewData["Title"] = "Lista de Tipos De Transporte";
}
<div class="text-center">


    <br />
    @if (TempData["MensagemSucesso"] != null)
    {
        <div class="alert alert-success" role="alert">
            <button type="button" class="btn btn-danger  btn-close" arial-label="close"></button>
            @TempData["MensagemSucesso"]
        </div>
    }
    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-danger" role="alert">
            <button type="button" class="btn btn-danger  btn-close" arial-label="close"></button>
            @TempData["MensagemErro"]
        </div>
    }

    <br />
    <h1 class="display-4 text-start">Tipos de Transporte</h1>

    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <a class="btn btn-primary" role="button" asp-controller="TipoDeTransporte" asp-action="Create">Adicionar Cargo</a>
    </div>
    <br />

    <table id="tabela" class="table">
        <thead class="table-dark">

            <tr>
                <th class="text-center" scope="col">Nome</th>
                <th class="text-center" scope="col">Ações</th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Any())
            {
                foreach (TipoDeTransporteModel tpTransporte in Model)
                {
                    <tr>
                        <input type="hidden" @tpTransporte.Id />
                        <td>@tpTransporte.NomeTransporte</td>
                        <td>
                            <div class="btn-group" role="group">
                                <a role="button" class="btn btn-warning" asp-route-id="@tpTransporte.Id" asp-controller="TipoDeTransporte" asp-action="Edit">Editar</a>
                                <a role="button" class="btn btn-danger" asp-route-id="@tpTransporte.Id" data-toggle="modal" data-target="#myModal_@tpTransporte.Id">Excluir</a>
                            </div>
                        </td>
                    </tr>

                    <div class="modal" id="myModal_@tpTransporte.Id">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <!-- Cabeçalho do Modal -->
                                <div class="modal-header">
                                    <h4 class="modal-title">Excluir Tipo de Transporte</h4>
                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                </div>

                                <!-- Corpo do Modal -->
                                <div class="modal-body">
                                    <p>Deseja realmente excluir o Tipo de Transporte de @tpTransporte.NomeTransporte ?</p>
                                </div>

                                <!-- Rodapé do Modal -->
                                <div class="modal-footer">
                                    <!-- Botão de cancelar -->
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                                    <!-- Botão de confirmar -->
                                    <a role="button" class="btn btn-danger" id="confirmDelete_@tpTransporte.Id" asp-route-id="@tpTransporte.Id" asp-controller="TipoDeTransporte" asp-action="Delete">Confirma</a>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            }
        </tbody>
    </table>

</div>