Controllers/FuncionariosController.cs
using Controle_de_Transporte_FrontEnd.Models;
using Controle_de_Transporte_FrontEnd.Service.Interface;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Net;

namespace Controle_de_Transporte_FrontEnd.Controllers
{
    public class FuncionariosController : Controller
    {
        private readonly IFuncionariosService _service;
        private readonly ICargoService _cargoService;
        private readonly IDepartamentoService _departService;
        public FuncionariosController(IFuncionariosService service, ICargoService cargoService, IDepartamentoService departService)
        {
            _service = service;
            _cargoService = cargoService;
            _departService = departService;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                var funcionarios = await _service.GetAllAsync();
                return View(funcionarios);
            }
            catch (Exception ex)
            {
                return StatusCode((int)HttpStatusCode.InternalServerError, new { Erro = ex.Message });
            }
        }

        public async Task<IActionResult> Details(int id)
        {
            try
            {
                var funcionario = await _service.GetByIdAsync(id);
                if (funcionario == null)
                {
                    return NotFound();
                }
                return View(funcionario);
            }
            catch (Exception ex)
            {
                return StatusCode((int)HttpStatusCode.InternalServerError, new { Erro = ex.Message });
            }
        }

        public async Task<IActionResult> Create()
        {
            var cargos = await ObterCargos();
            ViewBag.Cargos = new SelectList(cargos, "Id", "NomeCargo");
            
            var departamentos = await ObterDepartamentos();
            ViewBag.Departamentos = new SelectList(departamentos, "Id", "NomeDepartamento");

            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(FuncionariosModel funcionario)
        {
            if (ModelState.IsValid)
            {
                try
                {
                      var retorno = await _service.AddAsync(funcionario);
                        TempData["MensagemSucesso"] = "Funcionario cadastrado com sucesso!";
                        return RedirectToAction(nameof(Index));

                }
                catch (Exception ex)
                {
                    TempData["MensagemErro"] = "Erro ao cadastrado o Funcionario!";
                    return RedirectToAction("Index");
                }
            }
            return View(funcionario);
        }

        public async Task<IActionResult> Edit(int id)
        {

            try
            {
                var cargos = await ObterCargos();
                ViewBag.Cargos = new SelectList(cargos, "Id", "NomeCargo");
                var departamentos = await ObterDepartamentos();
                ViewBag.Departamentos = new SelectList(departamentos, "Id", "NomeDepartamento");

                var funcionario = await _service.GetByIdAsync(id);
                if (funcionario == null)
                {
                    return NotFound();
                }
                return View(funcionario);
            }
            catch (Exception ex)
            {
                return StatusCode((int)HttpStatusCode.InternalServerError, new { Erro = ex.Message });
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, FuncionariosModel funcionarios)
        {
            if (id != funcionarios.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _service.UpdateAsync(funcionarios);
                    TempData["MensagemSucesso"] = "Funcionario atualizar com sucesso!";
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    TempData["MensagemErro"] = "Erro ao atualizar o Funcionario!";
                    return RedirectToAction("Index");
                }
            }
            return View(funcionarios);
        }

        public async Task<IActionResult> Delete(int id)
        {
            try
            {
              bool funcionario = await _service.DeleteAsync(id);
                if (funcionario)
                {
                    TempData["MensagemSucesso"] = "Funcionario excluir com sucesso!";
                }
                else
                {
                    TempData["MensagemErro"] = "Erro ao excluir o Funcionario!";
                }
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                TempData["MensagemErro"] = "Erro ao excluir o Funcionario!";
                return RedirectToAction("Index");
            }
        }

        #region
        private async Task<List<CargoModel>> ObterCargos()
        {
            var cargo = new List<CargoModel>();


            var cargos = await _cargoService.GetAllAsync();


            if (cargos != null)
            {

                cargo.AddRange(cargos);
            }

            return cargo;
        }
       
        private async Task<List<DepartamentoModel>> ObterDepartamentos()
        {
            var departamento = new List<DepartamentoModel>();


            var departamentos = await _departService.GetAllAsync();


            if (departamentos != null)
            {

                departamento.AddRange(departamentos);
            }

            return departamento;
        }
        #endregion
    }
}

Views/Funcionarios/Create.cshtml
@model FuncionariosModel
@{
    ViewData["Title"] = "Adicionar Funcionario";
}
<div class="">

    <h1 class="display-4">Cadastrar Funcionario</h1>

    <form asp-controller="Funcionarios" asp-action="Create" method="post">

        <div class="container form-group">
            <div class="row">
                <div class="col-sm">
                    <label for="nome">Nome</label>
                    <input for="uppercase" type="text" asp-for="NomeFuncionario" class="form-control">
                    @Html.ValidationMessageFor(x => x.NomeFuncionario)
                </div> 
                <div class="col-sm">
                    <label for="matricula">Matricula</label>
                    <input for="uppercase" type="number" asp-for="Matricula" class="form-control">
                    @Html.ValidationMessageFor(x => x.Matricula)
                </div>
                <div class="col-sm">
                    @Html.LabelFor(model => model.CargoId, "Cargos", new { @class = "control-label" })
                    @Html.DropDownListFor(model => model.CargoId, ViewBag.Cargos as SelectList, "Selecione...", new { @class = "form-control" })
                </div> 
                <div class="col-sm">
                    @Html.LabelFor(model => model.DepartamentoId, "Departamentos", new { @class = "control-label" })
                    @Html.DropDownListFor(model => model.DepartamentoId, ViewBag.Departamentos as SelectList, "Selecione...", new { @class = "form-control" })
                </div>

            </div>

            <br />
            <button type="submit" class="btn btn-primary">Adicionar</button>
            <a class="btn btn-secondary" asp-controller="Funcionarios" asp-action="Index" role="button"> Voltar</a>
    </form>

</div>

Views/Funcionarios/Edit.cshtml
@model FuncionariosModel
@{
    ViewData["Title"] = "Editar Funcionario";
}
<div class="">
    @if (TempData["MensagemSucesso"] != null)
    {
        <div class="alert alert-success" role="alert">
            <button type="button" class="btn btn-danger  btn-close" arial-label="close"></button>
            @TempData["MensagemSucesso"]
        </div>
    }
    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-danger" role="alert">
            A simple danger alert—check it out!
            <button type="button" class="btn btn-danger  btn-close" arial-label="close"></button>
            @TempData["MensagemErro"]
        </div>
    }

    <br />
    <h1 class="display-4">Editar Funcionarios</h1>

    <form asp-controller="Funcionarios" asp-action="Edit" method="post">

        <input type="hidden" asp-for="Id" />
        

        <div class="container form-group">
            <div class="row">
                <div class="col-sm">
                    <label for="nome">Nome</label>
                    <input for="uppercase" type="text" asp-for="NomeFuncionario" class="form-control">
                    @Html.ValidationMessageFor(x => x.NomeFuncionario)
                </div> 
                <div class="col-sm">
                    <label for="matricula">Matricula</label>
                    <input for="uppercase" type="number" asp-for="Matricula" class="form-control">
                    @Html.ValidationMessageFor(x => x.Matricula)
                </div>
                <div class="col-sm">
                    @Html.LabelFor(model => model.CargoId, "Cargo", new { @class = "control-label" })
                    @Html.DropDownListFor(model => model.CargoId, ViewBag.Cargos as SelectList, "", new { @class = "form-control" })
                </div> 
                <div class="col-sm">
                    @Html.LabelFor(model => model.DepartamentoId, "Departamento", new { @class = "control-label" })
                    @Html.DropDownListFor(model => model.DepartamentoId, ViewBag.Departamentos as SelectList, "", new { @class = "form-control" })
                </div>
            </div>
        </div>
        <br />
        <button type="submit" class="btn btn-primary">Alterar</button>
        <a class="btn btn-secondary" asp-controller="Funcionarios" asp-action="Index" role="button"> Voltar</a>
    </form>

</div>

Views/Funcionarios/Index.cshtml
@model List<FuncionariosModel>
@{
    ViewData["Title"] = "Lista de Funcionarios";
}
<div class="text-center">


    <br />
    @if (TempData["MensagemSucesso"] != null)
    {
        <div class="alert alert-success" role="alert">
            <button type="button" class="btn btn-danger  btn-close" arial-label="close"></button>
            @TempData["MensagemSucesso"]
        </div>
    }
    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-danger" role="alert">
            <button type="button" class="btn btn-danger  btn-close" arial-label="close"></button>
            @TempData["MensagemErro"]
        </div>
    }

    <br />
    <h1 class="display-4 text-start">Funcionarios</h1>

    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <a class="btn btn-primary" role="button" asp-controller="Funcionarios" asp-action="Create">Adicionar Funcionario</a>
    </div>
    <br />

    <table id="tabela" class="table">
        <thead class="table-dark">

            <tr>
                <th class="text-center" scope="col">Nome</th>
                <th class="text-center" scope="col">Matricula</th>              
                <th class="text-center" scope="col">Cargo</th>
                <th class="text-center" scope="col">Departamento</th>
                <th class="text-center" scope="col">Ações</th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Any())
            {
                foreach (FuncionariosModel funcionarios in Model)
                {
                    <tr>
                        <input type="hidden" @funcionarios.Id />
                        <input type="hidden" @funcionarios.CargoId />
                        <input type="hidden" @funcionarios.DepartamentoId />
                        <td class="text-center">@funcionarios.NomeFuncionario</td>
                        <td class="text-center">@funcionarios.Matricula</td>
                        <td class="text-center">@funcionarios.Cargo.NomeCargo</td>
                        <td class="text-center">@funcionarios.Departamento.NomeDepartamento</td>
                        <td>
                            <div class="btn-group" role="group">
                                <a role="button" class="btn btn-warning" asp-route-id="@funcionarios.Id" asp-controller="Funcionarios" asp-action="Edit">Editar</a>
                                <a role="button" class="btn btn-danger" asp-route-id="@funcionarios.Id" data-toggle="modal" data-target="#myModal_@funcionarios.Id">Excluir</a>
                            </div>
                        </td>
                    </tr>

                    <div class="modal" id="myModal_@funcionarios.Id">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <!-- Cabeçalho do Modal -->
                                <div class="modal-header">
                                    <h4 class="modal-title">Excluir Funcionario</h4>
                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                </div>

                                <!-- Corpo do Modal -->
                                <div class="modal-body">
                                    <p>Deseja realmente excluir o Funcionario @funcionarios.NomeFuncionario ?</p>
                                </div>

                                <!-- Rodapé do Modal -->
                                <div class="modal-footer">
                                    <!-- Botão de cancelar -->
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                                    <!-- Botão de confirmar -->
                                    <a role="button" class="btn btn-danger" id="confirmDelete_@funcionarios.Id" asp-route-id="@funcionarios.Id" asp-controller="Funcionarios" asp-action="Delete">Confirma</a>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            }
        </tbody>
    </table>

</div>