Controllers/TransporteController.cs
using Controle_de_Transporte_FrontEnd.Models;
using Controle_de_Transporte_FrontEnd.Service.Interface;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Net;

namespace Controle_de_Transporte_FrontEnd.Controllers
{
    public class TransporteController : Controller
    {
        private readonly ITransporteService _service;
        private readonly IFuncionariosService _funcService;
        private readonly ITipodeTransporteService _tpService;
        private readonly IMatriculaTransporteService _matService;
        private readonly IManutencaoService _manuService;
        public TransporteController(ITransporteService service, IFuncionariosService funcService, ITipodeTransporteService tpService, IMatriculaTransporteService matService, IManutencaoService manuService)
        {
            _service = service;
            _funcService = funcService;
            _tpService = tpService;
            _matService = matService;
            _manuService = manuService;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                var transportes = await _service.GetAllAsync();
                return View(transportes);
            }
            catch (Exception ex)
            {
                return StatusCode((int)HttpStatusCode.InternalServerError, new { Erro = ex.Message });
            }
        }

        public async Task<IActionResult> Details(int id)
        {
            try
            {
                var transporte = await _service.GetByIdAsync(id);
                if (transporte == null)
                {
                    return NotFound();
                }
                return View(transporte);
            }
            catch (Exception ex)
            {
                return StatusCode((int)HttpStatusCode.InternalServerError, new { Erro = ex.Message });
            }
        }

        public async Task<IActionResult> Create()
        {
            var func = await ObterFuncionarios();
            ViewBag.Funcionarios = new SelectList(func, "Id", "NomeFuncionario");

            var mat = await ObterMatriculasTransporte();
            ViewBag.Matriculas = new SelectList(mat, "Id", "Matricula");
            
            var tp = await ObterTiposTransporte();
            ViewBag.TiposTransporte = new SelectList(tp, "Id", "NomeTransporte");
            
            var manu = await ObterManutencaos();
            ViewBag.Manutencoes = new SelectList(manu, "Id", "TipoManutencao");

            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(TransporteModel transporte)
        {
            if (ModelState.IsValid)
            {
                try
                {
                        var retorno = await _service.AddAsync(transporte);
                        TempData["MensagemSucesso"] = "Transporte cadastrado com sucesso!";
                        return RedirectToAction(nameof(Index));

                }
                catch (Exception ex)
                {
                    TempData["MensagemErro"] = "Erro ao cadastrado o Transporte!";
                    return RedirectToAction("Index");
                }
            }
            return View(transporte);
        }




        public async Task<IActionResult> Edit(int id)
        {

            try
            {
                var func = await ObterFuncionarios();
                ViewBag.Funcionarios = new SelectList(func, "Id", "NomeFuncionario");

                var mat = await ObterMatriculasTransporte();
                ViewBag.Matriculas = new SelectList(mat, "Id", "Matricula");

                var tp = await ObterTiposTransporte();
                ViewBag.TiposTransporte = new SelectList(tp, "Id", "NomeTransporte");

                var manu = await ObterManutencaos();
                ViewBag.Manutencoes = new SelectList(manu, "Id", "TipoManutencao");

                var transporte = await _service.GetByIdAsync(id);
                if (transporte == null)
                {
                    return NotFound();
                }
                return View(transporte);
            }
            catch (Exception ex)
            {
                return StatusCode((int)HttpStatusCode.InternalServerError, new { Erro = ex.Message });
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, TransporteModel transporte)
        {
            if (id != transporte.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _service.UpdateAsync(transporte);
                    TempData["MensagemSucesso"] = "Transporte atualizar com sucesso!";
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    TempData["MensagemErro"] = "Erro ao atualizar o Transporte!";
                    return RedirectToAction("Index");
                }
            }
            return View(transporte);
        }

        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                bool transporte = await _service.DeleteAsync(id);
                if (transporte)
                {
                    TempData["MensagemSucesso"] = "Transporte excluir com sucesso!";
                }
                else
                {
                    TempData["MensagemErro"] = "Erro ao excluir o Transporte!";
                }
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                TempData["MensagemErro"] = "Erro ao excluir o Transporte!";
                return RedirectToAction("Index");
            }
        }

        #region
        private async Task<List<TipoDeTransporteModel>> ObterTiposTransporte()
        {
            var tps = new List<TipoDeTransporteModel>();


            var tp = await _tpService.GetAllAsync();


            if (tps != null)
            {

                tp.AddRange(tps);
            }

            return tp;
        }
        
        private async Task<List<FuncionariosModel>> ObterFuncionarios()
        {
            var funcs = new List<FuncionariosModel>();


            var func = await _funcService.GetAllAsync();


            if (funcs != null)
            {

                func.AddRange(funcs);
            }

            return func;
        }
        
        private async Task<List<MatriculaTransporteModel>> ObterMatriculasTransporte()
        {
            var mats = new List<MatriculaTransporteModel>();


            var mat = await _matService.GetAllAsync();


            if (mats != null)
            {

                mat.AddRange(mats);
            }

            return mat;
        }
       
        private async Task<List<ManutencaoModel>> ObterManutencaos()
        {
            var manus = new List<ManutencaoModel>();


            var manu = await _manuService.GetAllAsync();


            if (manus != null)
            {

                manu.AddRange(manus);
            }

            return manu;
        }
        #endregion
    }
}

Views/Transporte/Create.cshtml
@model TransporteModel
@{
    ViewData["Title"] = "Adicionar Transporte";
}
<div class="">

    <h1 class="display-4">Cadastrar Transporte</h1>

    <form asp-controller="Transporte" asp-action="Create" method="post">

        <div class="container form-group">
            <div class="row">               
                <div class="col-sm">
                    @Html.LabelFor(model => model.FuncionarioId, "Funcionarios", new { @class = "control-label" })
                    @Html.DropDownListFor(model => model.FuncionarioId, ViewBag.Funcionarios as SelectList, "Selecione...", new { @class = "form-control" })
                </div>
                <div class="col-sm">
                    @Html.LabelFor(model => model.MatriculaTransporteId, "Matricula do Trnasporte", new { @class = "control-label" })
                    @Html.DropDownListFor(model => model.MatriculaTransporteId, ViewBag.Matriculas as SelectList, "Selecione...", new { @class = "form-control" })
                </div> 
                <div class="col-sm">
                    @Html.LabelFor(model => model.TipoTransporteId, "Tipo de Transporte", new { @class = "control-label" })
                    @Html.DropDownListFor(model => model.TipoTransporteId, ViewBag.TiposTransporte as SelectList, "Selecione...", new { @class = "form-control" })
                </div>
                <div class="col-sm">
                    @Html.LabelFor(model => model.ManutencaoId, "Tipo de Manutenção", new { @class = "control-label" })
                    @Html.DropDownListFor(model => model.ManutencaoId, ViewBag.Manutencoes as SelectList, "Selecione...", new { @class = "form-control" })
                </div>
            </div>
            <div class="row">
                <div class="col-sm">
                    <label for="data">Data Aquisição</label>
                    <input for="uppercase" type="date" asp-for="DataInicio" class="form-control">
                    @Html.ValidationMessageFor(x => x.DataInicio)
                </div>
                <div class="col-sm">
                    <label for="data">Data Devolução</label>
                    <input for="uppercase" type="date" asp-for="DataFim" class="form-control">
                    @Html.ValidationMessageFor(x => x.DataFim)
                </div>
            </div>
        </div>

            <br />
            <button type="submit" class="btn btn-primary">Adicionar</button>
            <a class="btn btn-secondary" asp-controller="Transporte" asp-action="Index" role="button"> Voltar</a>
    </form>

</div>

Views/Transporte/Edit.cshtml
@model TransporteModel
@{
    ViewData["Title"] = "Editar Transporte";
}
<div class="">
    @if (TempData["MensagemSucesso"] != null)
    {
        <div class="alert alert-success" role="alert">
            <button type="button" class="btn btn-danger  btn-close" arial-label="close"></button>
            @TempData["MensagemSucesso"]
        </div>
    }
    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-danger" role="alert">
            A simple danger alert—check it out!
            <button type="button" class="btn btn-danger  btn-close" arial-label="close"></button>
            @TempData["MensagemErro"]
        </div>
    }

    <br />
    <h1 class="display-4">Editar Transporte</h1>

    <form asp-controller="Transporte" asp-action="Edit" method="post">

        <input type="hidden" asp-for="Id" />
        

        <div class="container form-group">
            <div class="row">              
                <div class="col-sm">
                    @Html.LabelFor(model => model.FuncionarioId, "Funcionario", new { @class = "control-label" })
                    @Html.DropDownListFor(model => model.FuncionarioId, ViewBag.Funcionarios as SelectList, "", new { @class = "form-control" })
                </div>
                <div class="col-sm">
                    @Html.LabelFor(model => model.MatriculaTransporteId, "Matricula do Transporte", new { @class = "control-label" })
                    @Html.DropDownListFor(model => model.MatriculaTransporteId, ViewBag.Matriculas as SelectList, "", new { @class = "form-control" })
                </div> 
                <div class="col-sm">
                    @Html.LabelFor(model => model.TipoTransporteId, "Tipo de Transporte", new { @class = "control-label" })
                    @Html.DropDownListFor(model => model.TipoTransporteId, ViewBag.TiposTransporte as SelectList, "", new { @class = "form-control" })
                </div>
                <div class="col-sm">
                    @Html.LabelFor(model => model.ManutencaoId, "Tipo de Manutenção", new { @class = "control-label" })
                    @Html.DropDownListFor(model => model.ManutencaoId, ViewBag.Manutencoes as SelectList, "", new { @class = "form-control" })
                </div>
            </div>
            <div class="row">
                <div class="col-sm">
                    <label for="data">Data Aquisição</label>
                    <input for="uppercase" type="date" asp-for="DataInicio" class="form-control" readonly>
                    @Html.ValidationMessageFor(x => x.DataInicio)
                </div>
                <div class="col-sm">
                    <label for="data">Data Devolução</label>
                    <input for="uppercase" type="date" asp-for="DataFim" class="form-control">
                    @Html.ValidationMessageFor(x => x.DataFim)
                </div>
            </div>
        </div>
        <br />
        <button type="submit" class="btn btn-primary">Alterar</button>
        <a class="btn btn-secondary" asp-controller="Transporte" asp-action="Index" role="button"> Voltar</a>
    </form>

</div>

Views/Transporte/Index.cshtml
@model List<TransporteModel>
@{
    ViewData["Title"] = "Lista de Transporte";
}
<div class="text-center w-100">


    <br />
    @if (TempData["MensagemSucesso"] != null)
    {
        <div class="alert alert-success" role="alert">
            <button type="button" class="btn btn-danger  btn-close" arial-label="close"></button>
            @TempData["MensagemSucesso"]
        </div>
    }
    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-danger" role="alert">
            <button type="button" class="btn btn-danger  btn-close" arial-label="close"></button>
            @TempData["MensagemErro"]
        </div>
    }

    <br />
    <h1 class="display-4 text-start">Transportes</h1>

    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <a class="btn btn-primary" role="button" asp-controller="Transporte" asp-action="Create">Adicionar Transporte</a>
    </div>
    <br />

    <table id="tabela" class="table w-100">
        <thead class="table-dark">

            <tr>
                <th class="text-center" scope="col">Funcionario</th>
                <th class="text-center" scope="col">Matricula do Transporte</th>
                <th class="text-center" scope="col">Tipo de Transporte</th>
                <th class="text-center" scope="col">Tipo de Manutenção</th>
                <th class="text-center" scope="col">Data Aquisição</th>
                <th class="text-center" scope="col">Data Devolução</th>
                <th class="text-center" scope="col">Ações</th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Any())
            {
                foreach (TransporteModel transporte in Model)
                {
                    <tr>
                        <input type="hidden" @transporte.Id />
                        <input type="hidden" @transporte.FuncionarioId />
                        <input type="hidden" @transporte.MatriculaTransporteId />
                        <input type="hidden" @transporte.TipoTransporteId />
                        <input type="hidden" @transporte.ManutencaoId />

                        <td class="text-center">@transporte.Funcionario.NomeFuncionario</td>
                        <td class="text-center">@transporte.MatriculaTransporte.Matricula</td>
                        <td class="text-center">@transporte.TipoTransportes.NomeTransporte</td>
                        <td class="text-center">@((transporte.Manutencao != null) ? transporte.Manutencao.TipoManutencao : "")</td>
                        <td class="text-center">@transporte.DataInicio.ToShortDateString() </td>
                        <td class="text-center">@((transporte.DataFim != null) ? transporte.DataFim.GetValueOrDefault().ToShortDateString() : "")</td>

                        <td>
                            <div class="btn-group" role="group">
                                <a role="button" class="btn btn-warning btn-sm" asp-route-id="@transporte.Id" asp-controller="Transporte" asp-action="Edit">Editar</a>
                                <a role="button" class="btn btn-danger btn-sm" asp-route-id="@transporte.Id" data-toggle="modal" data-target="#myModal_@transporte.Id">Excluir</a>
                            </div>
                        </td>
                    </tr>

                    <div class="modal" id="myModal_@transporte.Id">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <!-- Cabeçalho do Modal -->
                                <div class="modal-header">
                                    <h4 class="modal-title">Excluir Transporte</h4>
                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                </div>

                                <!-- Corpo do Modal -->
                                <div class="modal-body">
                                    <p>Deseja realmente excluir o uso de transporte do @transporte.Funcionario.NomeFuncionario ?</p>
                                </div>

                                <!-- Rodapé do Modal -->
                                <div class="modal-footer">
                                    <!-- Botão de cancelar -->
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                                    <!-- Botão de confirmar -->
                                    <a role="button" class="btn btn-danger" id="confirmDelete_@transporte.Id" asp-route-id="@transporte.Id" asp-controller="Transporte" asp-action="Delete">Confirma</a>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            }
        </tbody>
    </table>

</div>